services:
  api:
    build: .
    container_name: "mini_banco"
    ports:
      - "3050:3050"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mini_banco_central
      - DB_USER=postgres
      - DB_PASS=postgres
    volumes:
      - .:/app
    restart: always
    command: sh -c "node src/seeders/seed.js && node src/server/server.js"
  
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mini_banco_central
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      GUNICORN_ACCESS_LOGFILE: /dev/null
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    
volumes:
  pgdata:
  pgadmin-data:
